pub mod errno;
pub mod handlers;

#[repr(C)]
pub struct SyscallArgs {
    pub nr:   u64,
    pub arg0: u64,
    pub arg1: u64,
    pub arg2: u64,
    pub arg3: u64,
    pub arg4: u64,
    pub arg5: u64,
}

pub type SyscallResult = i64;

#[unsafe(no_mangle)]
pub extern "C" fn syscall_dispatch(args: &SyscallArgs) -> SyscallResult {
    match args.nr {
        0  => handlers::io::sys_read(args),
        1  => handlers::io::sys_write(args),
        2  => handlers::io::sys_open(args),
        3  => handlers::io::sys_close(args),
        7  => handlers::io::sys_poll(args),
        8  => handlers::io::sys_lseek(args),
        16 => handlers::io::sys_ioctl(args),
        72 => handlers::io::sys_fcntl(args),
        17 => handlers::io::sys_pread64(args),
        18 => handlers::io::sys_pwrite64(args),
        19 => handlers::io::sys_readv(args),
        20 => handlers::io::sys_writev(args),
        22 => handlers::io::sys_pipe(args),
        23 => handlers::io::sys_select(args),
        32 => handlers::io::sys_dup(args),
        33 => handlers::io::sys_dup2(args),
        4   => handlers::fs::sys_stat(args),
        5   => handlers::fs::sys_fstat(args),
        6   => handlers::fs::sys_lstat(args),
        21  => handlers::fs::sys_access(args),
        78  => handlers::fs::sys_getdents(args),
        79  => handlers::fs::sys_getcwd(args),
        80  => handlers::fs::sys_chdir(args),
        81  => handlers::fs::sys_fchdir(args),
        82  => handlers::fs::sys_rename(args),
        83  => handlers::fs::sys_mkdir(args),
        84  => handlers::fs::sys_rmdir(args),
        85  => handlers::fs::sys_creat(args),
        86  => handlers::fs::sys_link(args),
        87  => handlers::fs::sys_unlink(args),
        88  => handlers::fs::sys_symlink(args),
        89  => handlers::fs::sys_readlink(args),
        217 => handlers::fs::sys_getdents64(args),
        257 => handlers::fs::sys_openat(args),
        262 => handlers::fs::sys_newfstatat(args),
        263 => handlers::fs::sys_unlinkat(args),
        9  => handlers::memory::sys_mmap(args),
        10 => handlers::memory::sys_mprotect(args),
        11 => handlers::memory::sys_munmap(args),
        12 => handlers::memory::sys_brk(args),
        25 => handlers::memory::sys_mremap(args),
        26 => handlers::memory::sys_msync(args),
        27 => handlers::memory::sys_mincore(args),
        28 => handlers::memory::sys_madvise(args),
        39  => handlers::process::sys_getpid(args),
        60  => handlers::process::sys_exit(args),
        102 => handlers::process::sys_getuid(args),
        104 => handlers::process::sys_getgid(args),
        107 => handlers::process::sys_geteuid(args),
        108 => handlers::process::sys_getegid(args),
        110 => handlers::process::sys_getppid(args),
        158 => handlers::process::sys_arch_prctl(args),
        186 => handlers::process::sys_gettid(args),
        231 => handlers::process::sys_exit_group(args),
        13  => handlers::signal::sys_rt_sigaction(args),
        14  => handlers::signal::sys_rt_sigprocmask(args),
        15  => handlers::signal::sys_rt_sigreturn(args),
        34  => handlers::signal::sys_pause(args),
        62  => handlers::signal::sys_kill(args),
        129 => handlers::signal::sys_rt_sigsuspend(args),
        130 => handlers::signal::sys_rt_sigpending(args),
        131 => handlers::signal::sys_sigaltstack(args),
        200 => handlers::signal::sys_tkill(args),
        234 => handlers::signal::sys_tgkill(args),
        35  => handlers::time::sys_nanosleep(args),
        96  => handlers::time::sys_gettimeofday(args),
        97  => handlers::time::sys_getrlimit(args),
        228 => handlers::time::sys_clock_gettime(args),
        229 => handlers::time::sys_clock_getres(args),
        230 => handlers::time::sys_clock_nanosleep(args),
        63  => handlers::process::sys_uname(args),
        218 => handlers::process::sys_set_tid_address(args),
        302 => handlers::time::sys_prlimit64(args),
        41 => handlers::net::sys_socket(args),
        42 => handlers::net::sys_connect(args),
        43 => handlers::net::sys_accept(args),
        44 => handlers::net::sys_sendto(args),
        45 => handlers::net::sys_recvfrom(args),
        46 => handlers::net::sys_sendmsg(args),
        47 => handlers::net::sys_recvmsg(args),
        48 => handlers::net::sys_shutdown(args),
        49 => handlers::net::sys_bind(args),
        50 => handlers::net::sys_listen(args),
        51 => handlers::net::sys_getsockname(args),
        52 => handlers::net::sys_getpeername(args),
        54 => handlers::net::sys_setsockopt(args),
        55 => handlers::net::sys_getsockopt(args),
        nr => {
            crate::kprintln!("[syscall] unhandled nr={}", nr);
            errno::ENOSYS
        }
    }
}
