// Shared boilerplate for sumi integration test programs.
//
// Each `data/<name>.rs` is a stand-alone single-file Rust program built into
// a static Linux ELF by `build.rs`. They all `include!("common.rs")` to pull
// in raw syscall wrappers, formatting helpers, the panic handler, and a
// `check!()` macro that exits the program with a non-zero status on failure.
//
// A test passes if it reaches `pass!()` (which exits with code 0). The kernel
// prints `[exit] code=N` and the host harness greps for `[exit] code=0`.

use core::arch::{asm, global_asm};
use core::panic::PanicInfo;

// `_start` shim. The Linux x86_64 ABI hands `_start` a 16-byte aligned `rsp`
// pointing at argc, but rustc compiles `extern "C" fn _start()` assuming the
// function-call ABI (`(rsp+8) % 16 == 0`), which is one off from what the
// kernel provides. The first SSE store generated by rustc then `#GP`s on
// the misaligned stack. We sidestep the whole thing with an asm shim that
// aligns rsp and tail-calls `sumi_main`. Tests define `sumi_main` and exit
// via the `pass!()` / `check!()` macros at any point.
global_asm!(
    ".global _start",
    "_start:",
    "    xor rbp, rbp",
    "    and rsp, -16",
    "    call sumi_main",
    "    mov rdi, rax",
    "    mov rax, 231", // exit_group
    "    syscall",
    "    ud2",
);

// Each test program implements `sumi_main` (declared by the test file as
// `pub extern "C" fn sumi_main() -> i32`). The asm `_start` shim above
// references it by symbol name; no Rust extern declaration needed.

// ── raw syscall ────────────────────────────────────────────────────────────

macro_rules! syscall_fn {
    ($name:ident($($arg:ident),*) [$($operand:tt)*]) => {
        #[inline]
        unsafe fn $name(nr: u64, $($arg: u64),*) -> i64 {
            let ret: i64;
            unsafe {
                asm!(
                    "syscall",
                    inlateout("rax") nr => ret,
                    $($operand)*
                    out("rcx") _,
                    out("r11") _,
                    options(nostack),
                );
            }
            ret
        }
    };
}

syscall_fn!(syscall0() []);
syscall_fn!(syscall1(a0) [in("rdi") a0,]);
syscall_fn!(syscall2(a0, a1) [in("rdi") a0, in("rsi") a1,]);
syscall_fn!(syscall3(a0, a1, a2) [in("rdi") a0, in("rsi") a1, in("rdx") a2,]);
syscall_fn!(
    syscall4(a0, a1, a2, a3) [in("rdi") a0, in("rsi") a1, in("rdx") a2, in("r10") a3,]
);
syscall_fn!(
    syscall5(a0, a1, a2, a3, a4) [
        in("rdi") a0,
        in("rsi") a1,
        in("rdx") a2,
        in("r10") a3,
        in("r8") a4,
    ]
);
syscall_fn!(
    syscall6(a0, a1, a2, a3, a4, a5) [
        in("rdi") a0,
        in("rsi") a1,
        in("rdx") a2,
        in("r10") a3,
        in("r8") a4,
        in("r9") a5,
    ]
);

// ── syscall numbers (Linux x86_64) ─────────────────────────────────────────

const SYS_READ: u64 = 0;
const SYS_WRITE: u64 = 1;
const SYS_OPEN: u64 = 2;
const SYS_CLOSE: u64 = 3;
const SYS_STAT: u64 = 4;
const SYS_FSTAT: u64 = 5;
const SYS_POLL: u64 = 7;
const SYS_LSEEK: u64 = 8;
const SYS_MMAP: u64 = 9;
const SYS_MPROTECT: u64 = 10;
const SYS_MUNMAP: u64 = 11;
const SYS_BRK: u64 = 12;
const SYS_IOCTL: u64 = 16;
const SYS_PREAD64: u64 = 17;
const SYS_PWRITE64: u64 = 18;
const SYS_READV: u64 = 19;
const SYS_WRITEV: u64 = 20;
const SYS_ACCESS: u64 = 21;
const SYS_PIPE: u64 = 22;
const SYS_DUP: u64 = 32;
const SYS_DUP2: u64 = 33;
const SYS_NANOSLEEP: u64 = 35;
const SYS_GETPID: u64 = 39;
const SYS_EXIT: u64 = 60;
const SYS_UNAME: u64 = 63;
const SYS_FCNTL: u64 = 72;
const SYS_TRUNCATE: u64 = 76;
const SYS_FTRUNCATE: u64 = 77;
const SYS_GETCWD: u64 = 79;
const SYS_CHDIR: u64 = 80;
const SYS_RENAME: u64 = 82;
const SYS_MKDIR: u64 = 83;
const SYS_RMDIR: u64 = 84;
const SYS_UNLINK: u64 = 87;
const SYS_GETRUSAGE: u64 = 98;
const SYS_TIMES: u64 = 100;
const SYS_GETUID: u64 = 102;
const SYS_GETGID: u64 = 104;
const SYS_GETEUID: u64 = 107;
const SYS_GETEGID: u64 = 108;
const SYS_GETPPID: u64 = 110;
const SYS_PRCTL: u64 = 157;
const SYS_ARCH_PRCTL: u64 = 158;
const SYS_GETTID: u64 = 186;
const SYS_FUTEX: u64 = 202;
const SYS_GETDENTS64: u64 = 217;
const SYS_SET_TID_ADDRESS: u64 = 218;
const SYS_CLOCK_GETTIME: u64 = 228;
const SYS_CLOCK_GETRES: u64 = 229;
const SYS_EXIT_GROUP: u64 = 231;
const SYS_GET_MEMPOLICY: u64 = 239;
const SYS_OPENAT: u64 = 257;
const SYS_MKDIRAT: u64 = 258;
const SYS_NEWFSTATAT: u64 = 262;
const SYS_UNLINKAT: u64 = 263;
const SYS_FALLOCATE: u64 = 285;
const SYS_PIPE2: u64 = 293;
const SYS_PRLIMIT64: u64 = 302;
const SYS_GETCPU: u64 = 309;
const SYS_GETRANDOM: u64 = 318;
const SYS_CLONE: u64 = 56;
const SYS_SCHED_YIELD: u64 = 24;

// ── flag constants ─────────────────────────────────────────────────────────

const O_RDONLY: u64 = 0;
const O_WRONLY: u64 = 1;
const O_RDWR: u64 = 2;
const O_CREAT: u64 = 0o100;
const O_TRUNC: u64 = 0o1000;

const PROT_READ: u64 = 0x1;
const PROT_WRITE: u64 = 0x2;
const MAP_PRIVATE: u64 = 0x02;
const MAP_ANONYMOUS: u64 = 0x20;

const SEEK_SET: u64 = 0;
const SEEK_CUR: u64 = 1;
const SEEK_END: u64 = 2;

const AT_FDCWD: i64 = -100;
const AT_EMPTY_PATH: u64 = 0x1000;

const CLOCK_REALTIME: u64 = 0;
const CLOCK_MONOTONIC: u64 = 1;

const ARCH_SET_FS: u64 = 0x1002;
const ARCH_GET_FS: u64 = 0x1003;

const CLONE_VM: u64 = 0x0000_0100;
const CLONE_FS: u64 = 0x0000_0200;
const CLONE_FILES: u64 = 0x0000_0400;
const CLONE_SIGHAND: u64 = 0x0000_0800;
const CLONE_THREAD: u64 = 0x0001_0000;
const CLONE_REQUIRED: u64 = CLONE_VM | CLONE_FS | CLONE_FILES | CLONE_SIGHAND | CLONE_THREAD;

const FUTEX_WAIT: u64 = 0;
const FUTEX_WAKE: u64 = 1;
const FUTEX_WAIT_BITSET: u64 = 9;

// ── thin wrappers around the syscalls used by tests ────────────────────────

#[inline]
fn sys_write(fd: i64, buf: &[u8]) -> i64 {
    unsafe { syscall3(SYS_WRITE, fd as u64, buf.as_ptr() as u64, buf.len() as u64) }
}

#[inline]
fn sys_read(fd: i64, buf: &mut [u8]) -> i64 {
    unsafe {
        syscall3(
            SYS_READ,
            fd as u64,
            buf.as_mut_ptr() as u64,
            buf.len() as u64,
        )
    }
}

#[inline]
fn sys_close(fd: i64) -> i64 {
    unsafe { syscall1(SYS_CLOSE, fd as u64) }
}

#[inline]
fn sys_poll(fds: *mut PollFd, nfds: usize, timeout_ms: i64) -> i64 {
    unsafe { syscall3(SYS_POLL, fds as u64, nfds as u64, timeout_ms as u64) }
}

#[inline]
fn sys_pipe(fds: &mut [i32; 2]) -> i64 {
    unsafe { syscall1(SYS_PIPE, fds.as_mut_ptr() as u64) }
}

#[inline]
fn sys_pipe2(fds: &mut [i32; 2], flags: u64) -> i64 {
    unsafe { syscall2(SYS_PIPE2, fds.as_mut_ptr() as u64, flags) }
}

#[inline]
fn sys_open(path: &[u8], flags: u64, mode: u64) -> i64 {
    // path must be NUL-terminated; helpers below use cstr literals.
    unsafe { syscall3(SYS_OPEN, path.as_ptr() as u64, flags, mode) }
}

#[inline]
fn sys_openat(dirfd: i64, path: &[u8], flags: u64, mode: u64) -> i64 {
    unsafe { syscall4(SYS_OPENAT, dirfd as u64, path.as_ptr() as u64, flags, mode) }
}

#[inline]
fn sys_lseek(fd: i64, offset: i64, whence: u64) -> i64 {
    unsafe { syscall3(SYS_LSEEK, fd as u64, offset as u64, whence) }
}

#[inline]
fn sys_dup(fd: i64) -> i64 {
    unsafe { syscall1(SYS_DUP, fd as u64) }
}

#[inline]
fn sys_dup2(old: i64, new: i64) -> i64 {
    unsafe { syscall2(SYS_DUP2, old as u64, new as u64) }
}

#[inline]
fn sys_fstat(fd: i64, buf: *mut u8) -> i64 {
    unsafe { syscall2(SYS_FSTAT, fd as u64, buf as u64) }
}

#[inline]
fn sys_stat(path: &[u8], buf: *mut u8) -> i64 {
    unsafe { syscall2(SYS_STAT, path.as_ptr() as u64, buf as u64) }
}

#[inline]
fn sys_pread64(fd: i64, buf: &mut [u8], offset: i64) -> i64 {
    unsafe {
        syscall4(
            SYS_PREAD64,
            fd as u64,
            buf.as_mut_ptr() as u64,
            buf.len() as u64,
            offset as u64,
        )
    }
}

#[inline]
fn sys_pwrite64(fd: i64, buf: &[u8], offset: i64) -> i64 {
    unsafe {
        syscall4(
            SYS_PWRITE64,
            fd as u64,
            buf.as_ptr() as u64,
            buf.len() as u64,
            offset as u64,
        )
    }
}

#[inline]
fn sys_truncate(path: &[u8], len: i64) -> i64 {
    unsafe { syscall2(SYS_TRUNCATE, path.as_ptr() as u64, len as u64) }
}

#[inline]
fn sys_ftruncate(fd: i64, len: i64) -> i64 {
    unsafe { syscall2(SYS_FTRUNCATE, fd as u64, len as u64) }
}

#[inline]
fn sys_fallocate(fd: i64, mode: u64, offset: i64, len: i64) -> i64 {
    unsafe { syscall4(SYS_FALLOCATE, fd as u64, mode, offset as u64, len as u64) }
}

#[inline]
fn sys_writev(fd: i64, iov: *const Iovec, iovcnt: usize) -> i64 {
    unsafe { syscall3(SYS_WRITEV, fd as u64, iov as u64, iovcnt as u64) }
}

#[inline]
fn sys_readv(fd: i64, iov: *const Iovec, iovcnt: usize) -> i64 {
    unsafe { syscall3(SYS_READV, fd as u64, iov as u64, iovcnt as u64) }
}

#[inline]
fn sys_brk(addr: u64) -> i64 {
    unsafe { syscall1(SYS_BRK, addr) }
}

#[inline]
fn sys_mmap(addr: u64, len: u64, prot: u64, flags: u64, fd: i64, offset: u64) -> i64 {
    unsafe { syscall6(SYS_MMAP, addr, len, prot, flags, fd as u64, offset) }
}

#[inline]
fn sys_munmap(addr: u64, len: u64) -> i64 {
    unsafe { syscall2(SYS_MUNMAP, addr, len) }
}

#[inline]
fn sys_mprotect(addr: u64, len: u64, prot: u64) -> i64 {
    unsafe { syscall3(SYS_MPROTECT, addr, len, prot) }
}

#[inline]
fn sys_clock_gettime(clk: u64, ts: *mut Timespec) -> i64 {
    unsafe { syscall2(SYS_CLOCK_GETTIME, clk, ts as u64) }
}

#[inline]
fn sys_clock_getres(clk: u64, ts: *mut Timespec) -> i64 {
    unsafe { syscall2(SYS_CLOCK_GETRES, clk, ts as u64) }
}

#[inline]
fn sys_times(tms: *mut Tms) -> i64 {
    unsafe { syscall1(SYS_TIMES, tms as u64) }
}

#[inline]
fn sys_getrusage(who: i64, usage: *mut Rusage) -> i64 {
    unsafe { syscall2(SYS_GETRUSAGE, who as u64, usage as u64) }
}

#[inline]
fn sys_get_mempolicy(
    mode: *mut i32,
    nodemask: *mut u64,
    maxnode: u64,
    addr: u64,
    flags: u64,
) -> i64 {
    unsafe {
        syscall5(
            SYS_GET_MEMPOLICY,
            mode as u64,
            nodemask as u64,
            maxnode,
            addr,
            flags,
        )
    }
}

#[inline]
fn sys_nanosleep(req: *const Timespec, rem: *mut Timespec) -> i64 {
    unsafe { syscall2(SYS_NANOSLEEP, req as u64, rem as u64) }
}

#[inline]
fn sys_getrandom(buf: &mut [u8], flags: u64) -> i64 {
    unsafe {
        syscall3(
            SYS_GETRANDOM,
            buf.as_mut_ptr() as u64,
            buf.len() as u64,
            flags,
        )
    }
}

#[inline]
fn sys_getpid() -> i64 {
    unsafe { syscall0(SYS_GETPID) }
}

#[inline]
fn sys_gettid() -> i64 {
    unsafe { syscall0(SYS_GETTID) }
}

#[inline]
fn sys_getuid() -> i64 {
    unsafe { syscall0(SYS_GETUID) }
}

#[inline]
fn sys_getgid() -> i64 {
    unsafe { syscall0(SYS_GETGID) }
}

#[inline]
fn sys_geteuid() -> i64 {
    unsafe { syscall0(SYS_GETEUID) }
}

#[inline]
fn sys_getegid() -> i64 {
    unsafe { syscall0(SYS_GETEGID) }
}

#[inline]
fn sys_getppid() -> i64 {
    unsafe { syscall0(SYS_GETPPID) }
}

#[inline]
fn sys_getcwd(buf: &mut [u8]) -> i64 {
    unsafe { syscall2(SYS_GETCWD, buf.as_mut_ptr() as u64, buf.len() as u64) }
}

#[inline]
fn sys_chdir(path: &[u8]) -> i64 {
    unsafe { syscall1(SYS_CHDIR, path.as_ptr() as u64) }
}

#[inline]
fn sys_rename(old_path: &[u8], new_path: &[u8]) -> i64 {
    unsafe { syscall2(SYS_RENAME, old_path.as_ptr() as u64, new_path.as_ptr() as u64) }
}

#[inline]
fn sys_mkdir(path: &[u8], mode: u64) -> i64 {
    unsafe { syscall2(SYS_MKDIR, path.as_ptr() as u64, mode) }
}

#[inline]
fn sys_mkdirat(dirfd: i64, path: &[u8], mode: u64) -> i64 {
    unsafe { syscall3(SYS_MKDIRAT, dirfd as u64, path.as_ptr() as u64, mode) }
}

#[inline]
fn sys_rmdir(path: &[u8]) -> i64 {
    unsafe { syscall1(SYS_RMDIR, path.as_ptr() as u64) }
}

#[inline]
fn sys_uname(buf: *mut u8) -> i64 {
    unsafe { syscall1(SYS_UNAME, buf as u64) }
}

#[inline]
fn sys_arch_prctl(code: u64, addr: u64) -> i64 {
    unsafe { syscall2(SYS_ARCH_PRCTL, code, addr) }
}

#[inline]
fn sys_ioctl(fd: i64, request: u64, arg: u64) -> i64 {
    unsafe { syscall3(SYS_IOCTL, fd as u64, request, arg) }
}

#[inline]
fn sys_fcntl(fd: i64, cmd: u64, arg: u64) -> i64 {
    unsafe { syscall3(SYS_FCNTL, fd as u64, cmd, arg) }
}

#[inline]
fn sys_futex(uaddr: *const u32, op: u64, val: u64) -> i64 {
    unsafe { syscall3(SYS_FUTEX, uaddr as u64, op, val) }
}

#[inline]
fn sys_futex6(
    uaddr: *const u32,
    op: u64,
    val: u64,
    timeout: *const Timespec,
    uaddr2: u64,
    val3: u64,
) -> i64 {
    unsafe {
        syscall6(
            SYS_FUTEX,
            uaddr as u64,
            op,
            val,
            timeout as u64,
            uaddr2,
            val3,
        )
    }
}

#[inline]
fn sys_prlimit64(pid: u64, resource: u64, new_lim: *const u8, old_lim: *mut u8) -> i64 {
    unsafe { syscall4(SYS_PRLIMIT64, pid, resource, new_lim as u64, old_lim as u64) }
}

#[inline]
fn sys_getcpu(cpu: *mut u32, node: *mut u32) -> i64 {
    unsafe { syscall3(SYS_GETCPU, cpu as u64, node as u64, 0) }
}

#[inline]
fn sys_set_tid_address(tidptr: *mut i32) -> i64 {
    unsafe { syscall1(SYS_SET_TID_ADDRESS, tidptr as u64) }
}

#[inline]
fn sys_getdents64(fd: i64, buf: &mut [u8]) -> i64 {
    unsafe {
        syscall3(
            SYS_GETDENTS64,
            fd as u64,
            buf.as_mut_ptr() as u64,
            buf.len() as u64,
        )
    }
}

#[inline]
fn sys_newfstatat(dirfd: i64, path: &[u8], buf: *mut u8, flags: u64) -> i64 {
    unsafe {
        syscall4(
            SYS_NEWFSTATAT,
            dirfd as u64,
            path.as_ptr() as u64,
            buf as u64,
            flags,
        )
    }
}

#[inline]
fn sys_access(path: &[u8], mode: u64) -> i64 {
    unsafe { syscall2(SYS_ACCESS, path.as_ptr() as u64, mode) }
}

#[inline]
fn sys_unlink(path: &[u8]) -> i64 {
    unsafe { syscall1(SYS_UNLINK, path.as_ptr() as u64) }
}

#[inline]
fn sys_unlinkat(dirfd: i64, path: &[u8], flags: u64) -> i64 {
    unsafe { syscall3(SYS_UNLINKAT, dirfd as u64, path.as_ptr() as u64, flags) }
}

#[inline]
fn sys_prctl(opt: u64, a: u64, b: u64, c: u64, d: u64) -> i64 {
    unsafe { syscall6(SYS_PRCTL, opt, a, b, c, d, 0) }
}

#[inline]
fn sys_sched_yield() -> i64 {
    unsafe { syscall0(SYS_SCHED_YIELD) }
}

#[inline]
fn sys_clone(flags: u64, child_stack: u64, ptid: *mut i32, ctid: *mut i32, tls: u64) -> i64 {
    unsafe { syscall5(SYS_CLONE, flags, child_stack, ptid as u64, ctid as u64, tls) }
}

#[inline]
fn exit(code: i32) -> ! {
    unsafe {
        let _ = syscall1(SYS_EXIT_GROUP, code as u64);
    }
    loop {}
}

/// Exit only the calling thread (raw `exit`, syscall 60) — as opposed to
/// `exit()` above (`exit_group`, syscall 231), which tears down the whole
/// VM. Used by tests that clone() worker threads and need each one to
/// terminate individually while the main thread keeps running.
#[inline]
fn exit_thread(code: i32) -> ! {
    unsafe {
        let _ = syscall1(SYS_EXIT, code as u64);
    }
    loop {}
}

// ── helper structs ─────────────────────────────────────────────────────────

#[repr(C)]
struct Timespec {
    tv_sec: i64,
    tv_nsec: i64,
}

#[repr(C)]
struct Tms {
    tms_utime: i64,
    tms_stime: i64,
    tms_cutime: i64,
    tms_cstime: i64,
}

#[repr(C)]
struct Timeval {
    tv_sec: i64,
    tv_usec: i64,
}

#[repr(C)]
struct Rusage {
    ru_utime: Timeval,
    ru_stime: Timeval,
    ru_rest: [i64; 14],
}

#[repr(C)]
struct Iovec {
    iov_base: *mut u8,
    iov_len: usize,
}

#[repr(C)]
struct PollFd {
    fd: i32,
    events: i16,
    revents: i16,
}

// Linux x86_64 stat layout (matches sumi-abi::stat::Stat).
#[repr(C)]
#[derive(Clone, Copy)]
struct Stat {
    st_dev: u64,
    st_ino: u64,
    st_nlink: u64,
    st_mode: u32,
    st_uid: u32,
    st_gid: u32,
    __pad0: u32,
    st_rdev: u64,
    st_size: i64,
    st_blksize: i64,
    st_blocks: i64,
    st_atime: u64,
    st_atime_nsec: u64,
    st_mtime: u64,
    st_mtime_nsec: u64,
    st_ctime: u64,
    st_ctime_nsec: u64,
    __unused: [i64; 3],
}

#[repr(C)]
#[derive(Clone, Copy)]
struct Rlimit {
    rlim_cur: u64,
    rlim_max: u64,
}

#[repr(C)]
struct LinuxDirent64 {
    d_ino: u64,
    d_off: i64,
    d_reclen: u16,
    d_type: u8,
    // d_name follows (variable length)
}

const RLIMIT_STACK: u64 = 3;

// ── output helpers ─────────────────────────────────────────────────────────

#[inline]
fn print(s: &[u8]) {
    let _ = sys_write(1, s);
}

fn print_int(mut n: i64) {
    let mut buf = [0u8; 24];
    let mut i = buf.len();
    let neg = n < 0;
    if neg {
        n = -n;
    }
    if n == 0 {
        i -= 1;
        buf[i] = b'0';
    } else {
        while n > 0 {
            i -= 1;
            buf[i] = b'0' + (n % 10) as u8;
            n /= 10;
        }
    }
    if neg {
        i -= 1;
        buf[i] = b'-';
    }
    print(&buf[i..]);
}

// ── failure helpers ────────────────────────────────────────────────────────

#[allow(unused_macros)]
macro_rules! fail {
    ($($arg:tt)*) => {{
        print(b"FAIL: ");
        $(print($arg);)*
        print(b"\n");
        exit(1);
    }};
}

#[allow(unused_macros)]
macro_rules! check {
    ($cond:expr) => {
        if !$cond {
            print(b"FAIL: ");
            print(stringify!($cond).as_bytes());
            print(b"\n");
            exit(1);
        }
    };
    ($cond:expr, $msg:expr) => {
        if !$cond {
            print(b"FAIL: ");
            print($msg);
            print(b": ");
            print(stringify!($cond).as_bytes());
            print(b"\n");
            exit(1);
        }
    };
}

#[allow(unused_macros)]
macro_rules! check_eq {
    ($left:expr, $right:expr) => {{
        let l = $left as i64;
        let r = $right as i64;
        if l != r {
            print(b"FAIL: ");
            print(stringify!($left).as_bytes());
            print(b" = ");
            print_int(l);
            print(b" != ");
            print_int(r);
            print(b" (");
            print(stringify!($right).as_bytes());
            print(b")\n");
            exit(1);
        }
    }};
}

#[allow(unused_macros)]
macro_rules! pass {
    () => {
        exit(0)
    };
}

// ── panic handler ──────────────────────────────────────────────────────────

#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    print(b"PANIC\n");
    exit(2)
}

// libcore references DW.ref.rust_eh_personality from its precompiled
// .eh_frame even when panic=abort is in effect. We never unwind, so a
// dummy symbol is enough to satisfy the linker.
#[unsafe(no_mangle)]
extern "C" fn rust_eh_personality() {}

// rustc emits direct calls to memset/memcpy/memmove/memcmp from
// compiler-builtins. With `-nodefaultlibs` we don't get them from libc
// either. Provide minimal byte-wise implementations — performance is
// irrelevant for tests.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn memset(dst: *mut u8, val: i32, n: usize) -> *mut u8 {
    let mut i = 0;
    while i < n {
        unsafe {
            *dst.add(i) = val as u8;
        }
        i += 1;
    }
    dst
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn memcpy(dst: *mut u8, src: *const u8, n: usize) -> *mut u8 {
    let mut i = 0;
    while i < n {
        unsafe {
            *dst.add(i) = *src.add(i);
        }
        i += 1;
    }
    dst
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn memmove(dst: *mut u8, src: *const u8, n: usize) -> *mut u8 {
    if (dst as usize) < (src as usize) {
        let mut i = 0;
        while i < n {
            unsafe {
                *dst.add(i) = *src.add(i);
            }
            i += 1;
        }
    } else {
        let mut i = n;
        while i > 0 {
            i -= 1;
            unsafe {
                *dst.add(i) = *src.add(i);
            }
        }
    }
    dst
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn memcmp(a: *const u8, b: *const u8, n: usize) -> i32 {
    let mut i = 0;
    while i < n {
        let av = unsafe { *a.add(i) };
        let bv = unsafe { *b.add(i) };
        if av != bv {
            return av as i32 - bv as i32;
        }
        i += 1;
    }
    0
}
