//! Build script for sumi-integration-tests.
//!
//! Compiles every test program in `data/` into a static Linux ELF binary
//! and generates one `#[test]` per binary in `$OUT_DIR/generated_tests.rs`.
//!
//! Three test categories are supported:
//!
//! * `data/syscalls/*.rs` — single-file `no_std` Rust programs that
//!   `include!("../common.rs")` for raw syscall wrappers. Compiled with
//!   `rustc` directly into a static `x86_64-unknown-linux-gnu` ELF.
//!
//! * `data/glibc/*.c` — C programs linked against the host's glibc.
//!   Compiled with `gcc -O2 -march=x86-64-v2` (the v2 cap matches what
//!   sumi can execute — see `cpuid_mask.rs`). The resulting binary
//!   resolves its dynamic linker and libc against the host filesystem
//!   when sumi is invoked with `--share /`.
//!
//! * `data/rust_std/*.rs` — single-file Rust programs that use `std`.
//!   Compiled with `rustc --target x86_64-unknown-linux-musl` with
//!   static musl linkage and `-no-pie` so the result is a plain ET_EXEC
//!   that sumi can load without any runtime. This exercises Rust's
//!   standard library startup path, independently from glibc.
//!
//! Generated test names are grouped into one `mod` per category for
//! cleaner `cargo test` output.

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const COMMON_FILE: &str = "common.rs";

/// Source files in `data/syscalls/` whose `#[test]` is written manually
/// in `tests/test_launcher.rs` (typically because they assert on a
/// non-zero exit code, which `run_test` does not support). The build
/// script must NOT auto-generate a `#[test]` for these — it would
/// always fail with "expected 0".
const MANUAL_SYSCALL_TESTS: &[&str] = &["exit_seven", "exit_group_kills_all", "tcp_epoll_loopback"];

/// Source files in `data/glibc/` whose `#[test]` is written manually
/// in `tests/test_launcher.rs` (e.g. because they require multiple vCPUs
/// via `run_test_smp` instead of the single-vCPU `run_test`).
const MANUAL_GLIBC_TESTS: &[&str] = &["preempt_timer"];

const RUST_NO_STD_TARGET: &str = "x86_64-unknown-linux-gnu";
const RUST_STD_TARGET: &str = "x86_64-unknown-linux-musl";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let data_dir = manifest_dir.join("data");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let bin_dir = out_dir.join("bin");
    fs::create_dir_all(&bin_dir).expect("create bin dir");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");
    println!("cargo:rustc-env=BIN_DIR={}", bin_dir.display());

    let common = data_dir.join(COMMON_FILE);
    println!("cargo:rerun-if-changed={}", common.display());

    let syscalls_tests = collect_sources(&data_dir.join("syscalls"), "rs");
    let glibc_tests = collect_sources(&data_dir.join("glibc"), "c");
    let rust_std_tests = collect_sources(&data_dir.join("rust_std"), "rs");

    for src in &syscalls_tests {
        let name = file_stem(src);
        let out = bin_dir.join("syscalls").join(&name);
        compile_rust_no_std(src, &out);
        println!("cargo:rerun-if-changed={}", src.display());
    }

    for src in &glibc_tests {
        let name = file_stem(src);
        let out = bin_dir.join("glibc").join(&name);
        compile_c(src, &out);
        println!("cargo:rerun-if-changed={}", src.display());
    }

    for src in &rust_std_tests {
        let name = file_stem(src);
        let out = bin_dir.join("rust_std").join(&name);
        compile_rust_std(src, &out);
        println!("cargo:rerun-if-changed={}", src.display());
    }

    let mut generated = String::from(
        "// AUTO-GENERATED by build.rs — do not edit.\n\
         // One #[test] per data/ test program, grouped by category.\n",
    );

    emit_category(&mut generated, "syscalls", &syscalls_tests);
    emit_category(&mut generated, "glibc", &glibc_tests);
    emit_category(&mut generated, "rust_std", &rust_std_tests);

    fs::write(out_dir.join("generated_tests.rs"), generated).expect("write generated_tests.rs");
}

fn emit_category(out: &mut String, category: &str, sources: &[PathBuf]) {
    if sources.is_empty() {
        return;
    }
    // Detect sanitized-identifier collisions inside a category. Two source
    // files whose stems differ only in punctuation (e.g. `foo.bar.rs` and
    // `foo_bar.rs`) would both map to `foo_bar`, and cargo test would fail
    // with a cryptic duplicate-definition error. Fail the build up front
    // with a clear message instead.
    let mut seen: HashSet<String> = HashSet::new();
    out.push_str(&format!("mod {category} {{\n"));
    for src in sources {
        let name = file_stem(src);
        // Skip tests that have a hand-written #[test] in test_launcher.rs
        // (typically those that assert on a non-zero exit code or require
        // multiple vCPUs).
        if category == "syscalls" && MANUAL_SYSCALL_TESTS.contains(&name.as_str()) {
            continue;
        }
        if category == "glibc" && MANUAL_GLIBC_TESTS.contains(&name.as_str()) {
            continue;
        }
        let fn_name = sanitize_ident(&name);
        assert!(
            seen.insert(fn_name.clone()),
            "data/{category}/: file {} sanitizes to the identifier `{fn_name}`, \
             which collides with another file in the same category. Rename one.",
            src.display()
        );
        out.push_str(&format!(
            "    #[test]\n    fn {fn_name}() {{ sumi_integration_tests::run_test(\"{category}/{name}\"); }}\n",
        ));
    }
    out.push_str("}\n");
}

fn file_stem(p: &Path) -> String {
    p.file_stem()
        .and_then(|s| s.to_str())
        .expect("test file name is valid UTF-8")
        .to_string()
}

fn collect_sources(dir: &Path, ext: &str) -> Vec<PathBuf> {
    if !dir.exists() {
        return Vec::new();
    }
    let mut sources: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some(ext))
        .collect();
    sources.sort();
    sources
}

/// Replace characters that are invalid in a Rust identifier with `_`.
/// Lossy (punctuation collapses), so `emit_category` also checks for
/// sanitized-name collisions within a category.
fn sanitize_ident(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    for (i, c) in name.chars().enumerate() {
        if i == 0 && c.is_ascii_digit() {
            s.push('_');
        }
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    s
}

/// Compile a `data/syscalls/<name>.rs` into a static Linux ELF binary.
///
/// Compiles via direct `rustc` (no cargo) because each test program is a
/// single self-contained file. The resulting binary is `#![no_std]`,
/// defines its own `_start`, links statically, and never references libc.
fn compile_rust_no_std(src: &Path, out_bin: &Path) {
    compile_with(
        "rustc",
        &[
            "--edition=2024",
            "--target",
            RUST_NO_STD_TARGET,
            "-C",
            "panic=abort",
            "-C",
            "opt-level=2",
            "-C",
            "relocation-model=static",
            "-C",
            "link-arg=-nostartfiles",
            "-C",
            "link-arg=-static",
            "-C",
            "link-arg=-no-pie",
            "-A",
            "warnings",
            "-o",
        ],
        src,
        out_bin,
        &[],
        "failed to invoke rustc",
    );
}

/// Compile a `data/rust_std/<name>.rs` into a statically-linked musl ELF
/// binary using Rust's `std`.
///
/// `-C target-feature=+crt-static` + `-no-pie` + `relocation-model=static`
/// produce a plain ET_EXEC that sumi can load without any runtime support.
///
/// The host must have the `x86_64-unknown-linux-musl` target installed:
/// `rustup target add x86_64-unknown-linux-musl`.
fn compile_rust_std(src: &Path, out_bin: &Path) {
    compile_with(
        "rustc",
        &[
            "--edition=2024",
            "--target",
            RUST_STD_TARGET,
            "-C",
            "target-feature=+crt-static",
            "-C",
            "panic=abort",
            "-C",
            "opt-level=2",
            "-C",
            "relocation-model=static",
            "-C",
            "link-arg=-no-pie",
            "-A",
            "warnings",
            "-o",
        ],
        src,
        out_bin,
        &[],
        "failed to invoke rustc for rust_std test",
    );
}

/// Compile a `data/glibc/<name>.c` into a dynamically-linked ELF binary.
///
/// `-march=x86-64-v2` caps the ISA so gcc does not emit AVX/AVX2 in the
/// user binary itself; sumi keeps `CR4.OSXSAVE=0` (see
/// `sumi-vm/src/arch/x86_64/kvm/cpuid_mask.rs`), so anything higher would
/// `#UD` inside the guest before the program ever reaches `main`.
fn compile_c(src: &Path, out_bin: &Path) {
    compile_with(
        "gcc",
        &[
            "-O2",
            "-march=x86-64-v2",
            "-Wall",
            "-Wno-unused-result",
            "-o",
        ],
        src,
        out_bin,
        // -lm so any libm symbol (sqrt/sin/...) is satisfied unconditionally;
        // -lpthread for code that touches pthread_*; both are no-ops if unused.
        &["-lm", "-lpthread"],
        "failed to invoke gcc — is gcc installed?",
    );
}

fn compile_with(
    program: &str,
    args: &[&str],
    src: &Path,
    out_bin: &Path,
    tail_args: &[&str],
    expect_msg: &str,
) {
    if let Some(parent) = out_bin.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    let status = Command::new(program)
        .args(args)
        .arg(out_bin)
        .arg(src)
        .args(tail_args)
        .status()
        .expect(expect_msg);

    assert!(status.success(), "{program} failed for {}", src.display());
}
