//! Build script for sumi-integration-tests.
//!
//! Compiles every test program in `data/` into a static Linux ELF binary
//! and generates one `#[test]` per binary in `$OUT_DIR/generated_tests.rs`.
//!
//! Two test categories are supported:
//!
//! * `data/syscalls/*.rs` — single-file `no_std` Rust programs that
//!   `include!("../common.rs")` for raw syscall wrappers. Compiled with
//!   `rustc` directly into a static `x86_64-unknown-linux-gnu` ELF.
//!
//! * `data/glibc/*.c` — C programs linked against the host's glibc.
//!   Compiled with `gcc -O2 -march=x86-64-v2` (the v2 cap matches what
//!   sumi can execute — see `cpuid_mask.rs`). The resulting binary
//!   resolves its dynamic linker and libc against the host filesystem
//!   when sumi is invoked with `--share /`.
//!
//! Generated test names are grouped into `mod syscalls { … }` and
//! `mod glibc { … }` blocks for cleaner `cargo test` output.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const COMMON_FILE: &str = "common.rs";
const RUST_TARGET: &str = "x86_64-unknown-linux-gnu";

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let data_dir = manifest_dir.join("data");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let bin_dir = out_dir.join("bin");
    fs::create_dir_all(&bin_dir).expect("create bin dir");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=data");
    println!("cargo:rustc-env=BIN_DIR={}", bin_dir.display());

    let common = data_dir.join(COMMON_FILE);
    println!("cargo:rerun-if-changed={}", common.display());

    let syscalls_tests = collect_syscall_tests(&data_dir.join("syscalls"));
    let glibc_tests = collect_glibc_tests(&data_dir.join("glibc"));

    for src in &syscalls_tests {
        let name = file_stem(src);
        let out = bin_dir.join("syscalls").join(&name);
        compile_rust(src, &out);
        println!("cargo:rerun-if-changed={}", src.display());
    }

    for src in &glibc_tests {
        let name = file_stem(src);
        let out = bin_dir.join("glibc").join(&name);
        compile_c(src, &out);
        println!("cargo:rerun-if-changed={}", src.display());
    }

    let mut generated = String::from(
        "// AUTO-GENERATED by build.rs — do not edit.\n\
         // One #[test] per data/ test program, grouped by category.\n",
    );

    if !syscalls_tests.is_empty() {
        generated.push_str("mod syscalls {\n");
        for src in &syscalls_tests {
            let name = file_stem(src);
            let fn_name = sanitize_ident(&name);
            generated.push_str(&format!(
                "    #[test]\n    fn {fn_name}() {{ sumi_integration_tests::run_test(\"syscalls/{name}\"); }}\n",
            ));
        }
        generated.push_str("}\n");
    }

    if !glibc_tests.is_empty() {
        generated.push_str("mod glibc {\n");
        for src in &glibc_tests {
            let name = file_stem(src);
            let fn_name = sanitize_ident(&name);
            generated.push_str(&format!(
                "    #[test]\n    fn {fn_name}() {{ sumi_integration_tests::run_test(\"glibc/{name}\"); }}\n",
            ));
        }
        generated.push_str("}\n");
    }

    fs::write(out_dir.join("generated_tests.rs"), generated)
        .expect("write generated_tests.rs");
}

fn file_stem(p: &Path) -> String {
    p.file_stem()
        .and_then(|s| s.to_str())
        .expect("test file name is valid UTF-8")
        .to_string()
}

fn collect_syscall_tests(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return Vec::new();
    }
    let mut sources: Vec<PathBuf> = fs::read_dir(dir)
        .expect("read syscalls dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("rs"))
        .collect();
    sources.sort();
    sources
}

fn collect_glibc_tests(dir: &Path) -> Vec<PathBuf> {
    if !dir.exists() {
        return Vec::new();
    }
    let mut sources: Vec<PathBuf> = fs::read_dir(dir)
        .expect("read glibc dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("c"))
        .collect();
    sources.sort();
    sources
}

/// Replace characters that are invalid in a Rust identifier with `_`.
fn sanitize_ident(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    for (i, c) in name.chars().enumerate() {
        if i == 0 && c.is_ascii_digit() {
            s.push('_');
        }
        if c.is_ascii_alphanumeric() || c == '_' {
            s.push(c);
        } else {
            s.push('_');
        }
    }
    s
}

/// Compile a `data/syscalls/<name>.rs` into a static Linux ELF binary.
///
/// Compiles via direct `rustc` (no cargo) because each test program is a
/// single self-contained file. The resulting binary is `#![no_std]`,
/// defines its own `_start`, links statically, and never references libc.
fn compile_rust(src: &Path, out_bin: &Path) {
    if let Some(parent) = out_bin.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    let status = Command::new("rustc")
        .args([
            "--edition=2024",
            "--target",
            RUST_TARGET,
            "-C",
            "panic=abort",
            "-C",
            "opt-level=2",
            "-C",
            "relocation-model=static",
            "-C",
            "link-arg=-nostartfiles",
            "-C",
            "link-arg=-static",
            "-C",
            "link-arg=-no-pie",
            "-A",
            "warnings",
            "-o",
        ])
        .arg(out_bin)
        .arg(src)
        .status()
        .expect("failed to invoke rustc");

    assert!(status.success(), "rustc failed for {}", src.display());
}

/// Compile a `data/glibc/<name>.c` into a dynamically-linked ELF binary.
///
/// `-march=x86-64-v2` caps the ISA so gcc does not emit AVX/AVX2 in the
/// user binary itself; sumi keeps `CR4.OSXSAVE=0` (see
/// `sumi-vm/src/arch/x86_64/kvm/cpuid_mask.rs`), so anything higher would
/// `#UD` inside the guest before the program ever reaches `main`.
fn compile_c(src: &Path, out_bin: &Path) {
    if let Some(parent) = out_bin.parent() {
        fs::create_dir_all(parent).unwrap();
    }

    let status = Command::new("gcc")
        .args([
            "-O2",
            "-march=x86-64-v2",
            "-Wall",
            "-Wno-unused-result",
            "-o",
        ])
        .arg(out_bin)
        .arg(src)
        // -lm so any libm symbol (sqrt/sin/...) is satisfied unconditionally;
        // -lpthread for code that touches pthread_*; both are no-ops if unused.
        .args(["-lm", "-lpthread"])
        .status()
        .expect("failed to invoke gcc — is gcc installed?");

    assert!(status.success(), "gcc failed for {}", src.display());
}
